### ISSUE TITLE
Geen link!

### ISSUE THREAD

**Issue by vasilisvg** [roberrrt-s/css-to-the-rescue#1]
Ik kan het resultaat nergens bekijken

**Comment by roberrrt-s** [comment]
http://roberrrt-s.github.io/css-to-the-rescue/opdracht-1/

**Comment by vasilisvg** [comment]
En dat is maar goed ook, hahaha: https://github.com/roberrrt-s/css-to-the-rescue/blob/master/opdracht-1/style/style.css#L14

**Comment by roberrrt-s** [comment]
Nu wel :)! Ik heb intense ruzie met Github pages, veel conflictsituaties.
