### ISSUE TITLE
Erg lelijk

### ISSUE THREAD

**Issue by vasilisvg** [roberrrt-s/css-to-the-rescue#3]
Het is lastig beoordelen met zo'n idioot font.

**Comment by roberrrt-s** [comment]
![image](https://cloud.githubusercontent.com/assets/6113643/12859874/485cf986-cc59-11e5-9337-5b9f4bfc3673.png)

Ik heb 'm maar aangepast naar een maatschappelijk geaccepteerd lettertype.
