### ISSUE TITLE
Wat doet dit precies?

### ISSUE THREAD

**Issue by vasilisvg** [roberrrt-s/css-to-the-rescue#5]
Dit is shorthand voor drie dingen. Welke precies? 
https://github.com/roberrrt-s/css-to-the-rescue/blob/master/opdracht-1/style/style.css#L24

**Comment by roberrrt-s** [comment]
- Flex als in de shorthand voor flex shrink, basis en grow, maar in dit geval vertel ik hem hoeveel ruimte hij mag opnemen ten opzichte van de flex container.
