### ISSUE TITLE
Hoge specificity

### ISSUE THREAD

**Issue by vasilisvg** [roberrrt-s/css-to-the-rescue#6]
Er staan vaak flink wat selectors achter elkaar. Kijk eens of dat minder kan? Probeer nooit meer dan 3 selectors achter elkaar te zetten. Vaak is het helemaal niet nodig om zo specifiek te zijn, en vaak zijn er ook andere manieren om die specifieke elementen te stijlen, bijvoorbeeld met attribute selectors
https://github.com/roberrrt-s/css-to-the-rescue/blob/master/opdracht-1/style/style.css#L39

**Comment by vasilisvg** [comment]
Ik zie nog steeds hele lange selectors…

**Comment by roberrrt-s** [comment]
Oh, die commit is niet in mn master branvh doorgekomen
